[package]
name = "rusty-duke"
version = "0.1.0"
authors = ["Sixten Thames <sixten@vildmarksdata.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
